version: '3.9'

services:
  app:
    build: 
      context: .
    volumes:
      - static_data:/vol/web
    env_file:
      - ./.devenv/.env
    depends_on:
      - redis

  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "8080:8080" # 80 for prod
      #- "443:443" # uncomment in prod
    depends_on:
      - app

  redis:
    image: redis:latest
    command: ["redis-server", "--bind", "redis", "--port", "6379"]


volumes:
  static_data: